### PR TITLE
save terms using `localStorage`

### PR DESCRIPTION
**Pull request by Yokozuna59**

### CODE REVIEW

**Comment by mrbasel** [comment]
Looks good, but it would be better if the course names are also saved

**Comment by Yokozuna59** [comment]
@mrbasel Could you please highlight what parts would be affected? I'm still not familiar with the project structure yet nor react.

I'm aware that I would change this:

https://github.com/Yokozuna59/kfupm-gpa-calculator/blob/save-terms-using-local-storage/src/hooks/useTerms.js#L4

But not sure about the others.

**Comment by mrbasel** [comment]
@Yokozuna59 
You also need to do the following:
- Modify the name input field in `course.js` so that it's state is saved along with the course grade and credits
- Pass the course name to the `<Course />` component in `Term.js`

**Comment by Yokozuna59** [comment]
@mrbasel I'm not sure if it's working or not, I can't run it locally. But I modified the changes according to your feedback cac86b8.

**Comment by Yokozuna59** [comment]
@mrbasel It appears that the term name is not saved.

**Pull request merged**
